### ISSUE TITLE
Publication card file links don't open properly when proxied

### ISSUE THREAD

**Issue by BrianGilbert** [Realityloop/civictheme-vue#122]
**Describe the bug**
When clicking link you get error that path cannot be found, if you open the link in a new tab the file loads, change makes link target _blank

**To Reproduce**

**Expected behavior**

**Media**
If applicable, add screenshots or video to help explain your problem.

**Your Environment (please complete the following information):**

**Additional context**

**Comment by BrianGilbert** [comment]
Title needs to be targeted to _blank as well

**Comment by ItsVRK** [comment]
fixed in https://github.com/Realityloop/civictheme-vue/commit/b986f9f7112043207192e3fb8bca1fee9f816867

**Comment by BrianGilbert** [comment]
fixed in https://github.com/Realityloop/civictheme-vue/commit/b986f9f7112043207192e3fb8bca1fee9f816867
